### ISSUE TITLE
Caret '> Folder' vertical position not centered with folder

### ISSUE THREAD

**Issue by ipaintcode** [atom/tree-view#1163]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Caret icon in front of folder, when opened or closed is not vertically centered from an aesthetic view. _Not an issues with the popular file-icons package._

### Steps to Reproduce

1. Open directory, works best with many folders to show caret not centering

Current base style
```css
.list-tree.has-collapsable-children .list-nested-item > .list-item::before {
    position: relative;
    top: -1px;
    margin-right: 5px;
}
```

**Expected behavior:** Aestheticly the caret next to the folder (open or closed) should be vertically centered

Expect base style to fix vertical centering

```css
.list-tree.has-collapsable-children .list-nested-item > .list-item::before {
    position: relative;
    top: 2px;
    margin-right: 5px;
}
```

**Actual behavior:** N/A

**Reproduces how often:** 100%

### Versions

Atom    : 1.19.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
macOS: Verson 10.12.6 (16G29)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
