### ISSUE TITLE
[Feature request] Sticky directories

### ISSUE THREAD

**Issue by Exelord** [atom/tree-view#1250]
Hey,
when I'm working on big projects with a big structure I often lose myself where I'm and looking for the last parent. What do you think about adding sticky directories?
EG:

![sticky](https://user-images.githubusercontent.com/1469375/40240719-86674d58-5ab9-11e8-9f00-cd232139c83f.gif)

**Comment by 50Wliu** [comment]
When using the One themes, there should be an option starting with Atom 1.28 beta to allow sticky directories.  Themes -> the settings button -> "Make tree-view project headers sticky".

**Comment by Exelord** [comment]
"Make tree-view project headers sticky" - isn't it only for `projects`? not for all directories?

**Comment by 50Wliu** [comment]
Ah!  You're completely correct.  Is the GIF you showed a mockup or an actual implementation of sticky directories?

**Comment by Exelord** [comment]
is actual but this just a draft, I didn't focused on detailing, just on the concept. If you would like to reproduce it here is a snippet:

```less
.tree-view {
  .project-root-header {
    z-index: 2 !important;
  }

  .entries .expanded>.header {
    position: sticky;
    top: 30px;
    background-color: rgb(232, 228, 217);
    z-index: 1;
  }
}
```
