### ISSUE TITLE
save tree width?

### ISSUE THREAD

**Issue by rakkarage** [atom/tree-view#250]
possible to save tree width somewhere for a 'project' or folder or maybe globally idk
i like the double click to make tree exactly right width
i don't like doing it each time i open the project

thanks

**Comment by bitmanic** [comment]
For the record, here's how I achieved this: 

1. Navigate to `Atom > Open Your Stylesheet`
2. Add the following styles: `.tree-view-resizer { min-width: 300px; }`

This sets the sidebar to a minimum width of 300 pixels, but allows the user to make the sidebar wider if necessary. This is how I prefer my sidebar to function; if you'd like to set a maximum width instead, simply replace `min-width` with `max-width`. 

If you'd like to set a fixed with that isn't able to be changed via the Atom UI, replace step two with this:
```css
.tree-view-resizer {
  width: 300px !important;
}

.tree-view-resize-handle {
  display: none;
}
```
