### ISSUE TITLE
Folder Expand/Collapse Animations

### ISSUE THREAD

**Issue by SebastianSzturo** [atom/tree-view#358]
It would be nice to have a expand/collapse animation on folders and projects to feel more native.

![Screencast](https://s3.amazonaws.com/f.cl.ly/items/1A0v3e0r1p2V203Q282N/Screen_Recording_2015_02_08_at_07.gif)

Any thoughts on that?

**Comment by lee-dohm** [comment]
You should be able to do this yourself with CSS, I think. @simurai, any pointers?

**Comment by simurai** [comment]
@SebastianSzturo I played around a bit by adding animations. You can try it in your `styles.less` file:

```css
.tree-view {
  .entry.expanded > .entries {
    -webkit-animation: tree-view-expanded .4s cubic-bezier(.15,.7,.3, 1);
    -webkit-animation-fill-mode: forewards;
  }
  @-webkit-keyframes tree-view-expanded {
      0% { opacity: 0; transform: translateY(-10px); }
    100% { opacity: 1; transform: translateY(0); }
  }
}
```

![tree-view](https://cloud.githubusercontent.com/assets/378023/6122087/99890e4c-b131-11e4-8bde-e400ce8e0a51.gif)

But it's not that great and has some flaws:

1. When collapsing all the DOM elements get removed immediately, so there can't be any animation on them, only when expanding.
2. When expanding the elements below get pushed down without animation. Might be possible with `min-height`, but would be pretty hackish.

So to do it really well, some more effort would be needed. Maybe calculate all positions with JS and inline the CSS? Then expanding/collapsing can be more dynamic. But it should only be considered if performance will be smooth.

**Comment by SebastianSzturo** [comment]
@simurai Thank for looking into it! 
Seams like a more native implementation would come with more effort than I thought and maybe with some performance downsides. I am a big fan of your work at the new atom one templates. Do you think animations like that are generally a good idea?

**Comment by simurai** [comment]
> Do you think animations like that are generally a good idea?

Yeah, I think it would improve UX because you see where things come from and go back again. So it would help orientation. Also animating the tree-view or find&replace panels would be nice. But because they all change width/height, performance wouldn't look that smooth. So not sure. Maybe no animation is still better than choppy animation?

Adding animations on smaller things and if possible only use `opacity` and `transform` should be no problem though.

**Comment by abejfehr** [comment]
I've been trying to play around with this and I've been animating the expand/collapse by using CSS transitions on the `max-height` of the entries. But by default, a .collapsed entry is set to `display: none;` and I'd like to change it but I can't find where that's defined. Are those styles defined somewhere in the atom core?

**Comment by simurai** [comment]
@abejfehr The selector is:

```css
.list-tree.has-collapsable-children .list-nested-item.collapsed > .list-tree {
  display: none;
}
```

So you might can try to override that.
