### ISSUE TITLE
Allow sidebar to be a tiny bit more responsive.

### ISSUE THREAD

**Issue by envygeeks** [atom/tree-view#472]
Allow it to lay over the content. Say a user has a 1366-1900 screen and they do side-by-side view, they have just enough room for 80-100 chars so they hide the sidebar, it would be nice if they could kick on a responsive sidebar that instead of squishing the content overlays it and on click closes itself once a file is opened.

As far as the CSS, I was able to easily achieve this in my own editor with:

```less
@media (max-width: 1024px) {
  atom-panel-container.left {
    z-index: 1000;
    position: fixed;
    bottom: 0;
    top: 0;

    .tree-view-resizer {
      border-right: 1px solid #ccc;
    }
  }
}
```
