### ISSUE TITLE
Empty context menu when tree view doesn't take entire vertical space

### ISSUE THREAD

**Issue by olmokramer** [atom/tree-view#595]
After https://github.com/atom/tree-view/pull/579 was merged, the `.tree-view` doesn't extend vertically to the bottom of the `.tree-view-scroller` when only a few files/directories are visible. The problem is that context menu entries use the `.tree-view` selector, so when I right-click on space below the tree view the context menu is empty.

![image](https://cloud.githubusercontent.com/assets/3612514/10481659/707cbe10-7272-11e5-9255-5a07aaae3854.png)

**Comment by thomasjo** [comment]
I can easily reproduce this. Maybe @simurai has an idea for a quick fix?

**Comment by olmokramer** [comment]
Adding the following rules solves this for me. It won't work when packages add other elements to the `.tree-view-scroller`, but otherwise it should be fine. What are your thoughts @abe33 or @simurai?

```less
.tree-view-resizer {
  .tree-view-scroller {
    position: relative;
  }

  .tree-view {
    position: absolute;
    // the absolute positioning causes the list to not
    // fill horizontally, so set width: 100%
    width: 100%;
  }
}
```

**Comment by simurai** [comment]
Good point about the context menu.

Absolutely positioned tree-view makes the selection not go all the way to the right, when scrolled horizontally.

![screen shot 2015-10-15 at 11 25 20 am](https://cloud.githubusercontent.com/assets/378023/10503353/0dc15498-7330-11e5-801b-b4572519d275.png)

Not quite sure why there is that `10px` padding. Maybe we could add yet another flexbox also on the `.tree-view-scroller`. Then other packages can also inject other elements there.. basically the same as for `.tree-view-resizer` in #579.

```less
.tree-view-resizer {
  .tree-view-scroller {
    display: flex;
    flex-direction: column;
  }

  .tree-view {
    flex: 1;
  }
}
```
