### ISSUE TITLE
Stop Git Highlighting

### ISSUE THREAD

**Issue by meshakeeb** [atom/tree-view#657]
Hi, I want to disable the GIT highlighting in the treeview. Is that possible.

Thanks in Advance

**Comment by glangford** [comment]
@spyropress you can edit your stylesheet, see the discussion here:
<https://discuss.atom.io/t/how-to-remove-the-colors-from-the-file-tree/9142/17>

For Atom 1.2.3, I tested using the following (slightly different from the last suggestion in the discussion):
```less
.tree-view li.list-nested-item[class*='status-'] > .list-item {
    color: #fff !important;
}

.icon-file-text {
  color:#fff !important;
}
```

**Comment by lee-dohm** [comment]
Using the stylesheet to modify the colors to not differentiate the various states is the standard way of doing this. Let us know if @glangford's solution doesn't work for you.

**Comment by YourPsychiatrist** [comment]
This style seems to overwrite the text-color of specific style, howere icons and folders are still in status colors. Since i have no experience with LESS i don't know if it's even supposed to do that, but now it looks like something half way cooked. Using Atom version 1.3.2!

**Comment by lee-dohm** [comment]
@simurai Could you take a look at this and maybe update the README with info on a quick snippet to drop into your `styles.less` to disable the Git status colors in the tree view?

**Comment by glangford** [comment]
> This style seems to overwrite the text-color of specific style, howere icons and folders are still in status colors.

@YourPsychiatrist I retested again using 1.4.0, and it still works fine in my environment. After updating and saving styles.less, icons and folders are not in status colors. Not sure about 1.3.2.

**Comment by mnquintana** [comment]
Hmmm, it seems reasonable to to me to add a setting for `Enable VCS Coloring` like we have now for the tabs package. (It would default to enabled, though.)

**Comment by simurai** [comment]
How about this:

```less
// remove Git colors from tree-view
.tree-view {
  .status-modified,
  .status-added,
  .status-renamed,
  .status-removed {
    color: inherit !important; // remove diff color

    &.directory > .list-item {
      color: inherit !important; // remove diff color
    }
    &.directory.selected > .list-item {
      color: @text-color-selected !important; // add selected color
    }
  }
}
```

it `inherit`s the color, so it should work with any theme.
