### ISSUE TITLE
Difficult to recognize parent-child relation

### ISSUE THREAD

**Issue by Kiikurage** [atom/tree-view#662]
For example, take a look at this image.

![2015-11-29 13 32 19](https://cloud.githubusercontent.com/assets/3253117/11455416/dfea0f3e-96a1-11e5-9b9b-35f5514c4f6a.png)

`item-1-2` is looked like a child of `item-1-1`, but it is a child of `item-1` .

![2015-11-29 13 32 27](https://cloud.githubusercontent.com/assets/3253117/11455417/e36334c4-96a1-11e5-84fa-7ae405954a57.png)

I think it's because of the indent level.
In current design, the indent level is not same between folders and files.

So arrow-icons should be removed to make indent level same, and show folder states with opened/closed folder icons.

In user stylesheet, 

```
.list-tree.has-collapsable-children .list-nested-item > .list-item::before {
	opacity: 0 !important;
}
```

then it looks better.

![2015-11-29 14 12 29](https://cloud.githubusercontent.com/assets/3253117/11455446/94191ca6-96a3-11e5-8e10-a0ff0412a195.png)

Of course, it may be only my feeling and this design can be customized with user stylesheet,
so maybe it's not the important problem.

Please give your opinions.

**Comment by Kiikurage** [comment]
In user stylesheet, 

```
.list-tree.has-collapsable-children .list-nested-item > .list-item::before {
	opacity: 0 !important;
}
```

then

![2015-11-29 14 10 38](https://cloud.githubusercontent.com/assets/3253117/11455438/1db41476-96a3-11e5-8d0a-f3cae51b10fd.png)

**Comment by lee-dohm** [comment]
I don't see the difference.

With arrow:

![with-arrow](https://cloud.githubusercontent.com/assets/1038121/11459898/14e4601a-9696-11e5-9ce0-341db048fd7b.png)

Without arrow:

![without-arrow](https://cloud.githubusercontent.com/assets/1038121/11459900/1cbebf2e-9696-11e5-8cc9-f9ebbd61cf9f.png)

The alignment is exactly the same in both cases.

**Comment by simurai** [comment]
I think the issue is that folders have arrows and files not. So when you include the arrow, then the arrow of folders are not aligned with the file icons below that are on the same indent level.

Maybe the arrow could be more subtle so it doesn't get too much attention. Or when completely hiding the arrow, have two states of the folder icon. One for open and another one for closed.

**Comment by 50Wliu** [comment]
See also #629.

**Comment by simurai** [comment]
__Option 1__: Faded arrows

```less
.tree-view .directory > .list-item:before {
  opacity: .4;
}
```

![screen shot 2015-12-21 at 1 23 15 pm](https://cloud.githubusercontent.com/assets/378023/11923436/cf3da686-a7e6-11e5-947d-f3090a9cfa61.png)

Then the arrows are weaker and maybe makes it easier to see the indentation.

__Option 2__: Hidden arrows + different open icon

```less
.tree-view .directory {
  & > .list-item:before {
    visibility: hidden; // hide arrows
  }
  &.expanded > .list-item > .icon-file-directory:before {
    content: "\f0b1"; // different icon
  }
}
```

![screen shot 2015-12-21 at 1 22 44 pm](https://cloud.githubusercontent.com/assets/378023/11923443/eb7ca8c4-a7e6-11e5-8674-0ba76af32658.png)

The icon could be better, it's the symlink icon, so that might be confusing. Here a list of all icon codes shipped in Atom: https://github.com/atom/atom/blob/master/static/variables/octicon-utf-codes.less

**Comment by ProLoser** [comment]
Maybe you could have a `|` line when you hover over the tree / folder similar to how it's done in the IDE itself. If you hover the mouse over a file, you see a pipe along the left edge that helps you visualize the files ancestry. This allows us to preserve the folding icons which are pretty standard, and only clutters the UI upon user interaction intent vs constant clutter.

![image](https://cloud.githubusercontent.com/assets/67395/19173613/60c3894c-8bdd-11e6-8b59-789b6d0c1e4e.png)

**Comment by simurai** [comment]
@ProLoser That's a great idea! :clap: Here some fiddling with it:

```less
@import "ui-variables";

.tree-view .directory {
  & > .list-item:before {
    visibility: hidden; // hide arrows
  }
  .header.list-item:hover + .entries.list-tree {
    background: linear-gradient(to right, transparent 24px, @text-color-subtle 24px, @text-color-subtle 25px, transparent 25px);
  }
}
```

![borders](https://cloud.githubusercontent.com/assets/378023/19176959/cf3dd060-8c7f-11e6-9b8c-0e7bb421954c.gif)

It still keeps the arrows hidden so that the `|` line connects the folders.

**Comment by ProLoser** [comment]
Looks good except I noted in your demo that if you have a row selected the line doesn't show up on hover. Is that fixable too? Otherwise this actually looks great to me. Perhaps the highlighted folder would redundantly show this line too? Like when there is no mouse hover or in addition to the mouse hover?

**Comment by ProLoser** [comment]
Also, will using a `~` selector instead of a `+` selector be more versatile?

**Comment by simurai** [comment]
> if you have a row selected the line doesn't show up on hover

The line is underneath, so the selection would need to be semi-transparent.

> Perhaps the highlighted folder would redundantly show this line too? Like when there is no mouse hover or in addition to the mouse hover? Even if it's perhaps a muted line since the highlight will always be there(?) Maybe just during keyboard focus of the panel?

Yeah, maybe a muted line, so that when you hover, you see the line getting stronger.

> will using a `~` selector instead of a `+` selector be more versatile?

I think there is always just one sibling, but yeah, might not hurt to change it.

Here an updated version:

```less
.tree-view .selected:before {
  background: hsla(0,0%,100%,.1); // show lines underneath
}
.tree-view .directory {
  & > .list-item:before {
    visibility: hidden; // hide arrows
  }
  .selected > .header.list-item ~ .entries.list-tree {
    background: linear-gradient(to right, transparent 24px, lighten(@base-background-color, 10%) 24px, lighten(@base-background-color, 10%) 25px, transparent 25px);
  }
  .header.list-item:hover ~ .entries.list-tree {
    background: linear-gradient(to right, transparent 24px, @text-color-subtle 24px, @text-color-subtle 25px, transparent 25px);
  }
}
```

![tree-view](https://cloud.githubusercontent.com/assets/378023/19330790/79a82d26-911b-11e6-9be9-0cab1f67163e.gif)

**Comment by ProLoser** [comment]
That definitely looks perfect!

**Comment by ProLoser** [comment]
This is awesome! Can this make it into an upcoming release?

**Comment by simurai** [comment]
> Can this make it into an upcoming release?

Hmm.. a problem is that the selection needs to be semi-transparent and we would have to override themes.

Maybe better to keep it for your `styles.less`. Or a separate package.

**Comment by thomasjo** [comment]
Yeah, this makes more sense as a stylesheet tweak (or a package).

**Comment by ProLoser** [comment]
Would be nice if the styles worked better with the arrows.

**Comment by thomasjo** [comment]
Since we have no immediate plans to change the current implementation of the tree-view as far as visualization of parent-child relationship goes, and given the fact this can readily be customized via tweaking `styles.less` (or in a theme), I'm closing this issue.

**Comment by Ben3eeE** [comment]
I think this looks much better. Adding it to my stylesheet! Thanks @simurai @ProLoser 🙇

**Comment by simurai** [comment]
Just saw https://atom.io/packages/clean-ui the other day.

<img width="246" alt="68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f63646f6e6f6875652f636c65616e2d75692f6d61737465722f73637265656e73686f74732f747265652d766965772e706e67" src="https://cloud.githubusercontent.com/assets/378023/19460609/1a0b25f2-9518-11e6-90a9-7778693b49de.png">

It adds a dot in front of files so that it lines up with the arrows of closed folders. Should help in seeing the indent level.

**Comment by dzift** [comment]
What an awesome solution. Love it. However I would like to make one more adjustment. Not sure if it's possible.. Here is what mine looks like right now:

![indent](https://cloud.githubusercontent.com/assets/21025134/23793745/14e1b04c-058d-11e7-8bfc-67314a2f7ea6.png)

Selected and on hover share the same style.
I would like to add an extra pointer (dash?) to each item in a directory's scope like this:

![indent_goal](https://cloud.githubusercontent.com/assets/21025134/23793747/17e224ca-058d-11e7-82b5-2fcfde5a93d7.png)

Any ideas?

**Comment by simurai** [comment]
@dzift not exactly, but a little bit closer:

```less
// add dashes
.theme-clean-ui {
  .list-tree.has-collapsable-children li.list-item,
  .list-tree.has-collapsable-children .list-nested-item > .list-tree > li,
  .list-tree.has-collapsable-children .list-nested-item > .list-group > li {
    padding-left: 1em;
  }
  .list-item.file.entry {
    position: relative;
    &:after {
      content: "";
      position: absolute;
      border-top: 1px solid;
      top: 3em;
      left: -1em;
      width: 2em;
    }
  }
}
```

![screen shot 2017-03-29 at 2 21 34 pm](https://cloud.githubusercontent.com/assets/378023/24439742/13b251a6-148b-11e7-9cf8-a30fc3812925.png)
