### ISSUE TITLE
Option to not grey-out VCS hidden directories / files.

### ISSUE THREAD

**Issue by davidbarratt** [atom/tree-view#780]
Sometimes it can be really hard to read folders and filenames that are ignored in the VCS.

It would be really helpful to have an option to not grey them out, but show them the same as non-ignored path.

Or perhaps some other visual indicator that does not affect the legibility of the title.

**Comment by simurai** [comment]
It depends a bit on the theme, but adding the example below to your `styles.less` should work.

```less
@import "ui-variables";

// style ignored tree-view files
.tree-view .status-ignored .list-item {
  color: @text-color !important;
}
```

Or you could also use a different color, like `color: red !important;`.

**Comment by garygreen** [comment]
@simurai that works wonderfully. The only problem is the icons. I use setui icons and they are all missing on those files. It replaces the css with:

```css
atom-workspace .entries.list-tree .file.status-ignored .icon:before {
    content: '\E02B';
}
```

Makes it difficult to disable this without some javascript? Not even sure what events I would listen to in order to make it work...

**Comment by simurai** [comment]
@garygreen For the `seti-icons` package, this should work:

```less
// style ignored tree-view files
.tree-view .status-ignored .list-item,
.tree-view .status-ignored .icon:before {
  color: @text-color !important;
}
```
